/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WashRouteImport } from './routes/wash'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehicleIdRouteImport } from './routes/vehicle.$id'
import { Route as DriverIdRouteImport } from './routes/driver.$id'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHiresRouteImport } from './routes/_authenticated/hires'
import { Route as AuthenticatedDriverDashboardRouteImport } from './routes/_authenticated/driver-dashboard'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedVendorIndexRouteImport } from './routes/_authenticated/vendor.index'
import { Route as BookingQrCodeRouteImport } from './routes/booking.qr.$code'
import { Route as AuthenticatedMessagesBookingIdRouteImport } from './routes/_authenticated/messages.$bookingId'
import { Route as AuthenticatedVendorVehiclesNewRouteImport } from './routes/_authenticated/vendor.vehicles.new'
import { Route as AuthenticatedBookingsIdTripRouteImport } from './routes/_authenticated/bookings.$id.trip'
import { Route as AuthenticatedBookingsIdDisputeRouteImport } from './routes/_authenticated/bookings.$id.dispute'

const WashRoute = WashRouteImport.update({
  id: '/wash',
  path: '/wash',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleIdRoute = VehicleIdRouteImport.update({
  id: '/vehicle/$id',
  path: '/vehicle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIdRoute = DriverIdRouteImport.update({
  id: '/driver/$id',
  path: '/driver/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHiresRoute = AuthenticatedHiresRouteImport.update({
  id: '/hires',
  path: '/hires',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverDashboardRoute =
  AuthenticatedDriverDashboardRouteImport.update({
    id: '/driver-dashboard',
    path: '/driver-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorIndexRoute =
  AuthenticatedVendorIndexRouteImport.update({
    id: '/vendor/',
    path: '/vendor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BookingQrCodeRoute = BookingQrCodeRouteImport.update({
  id: '/booking/qr/$code',
  path: '/booking/qr/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMessagesBookingIdRoute =
  AuthenticatedMessagesBookingIdRouteImport.update({
    id: '/messages/$bookingId',
    path: '/messages/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorVehiclesNewRoute =
  AuthenticatedVendorVehiclesNewRouteImport.update({
    id: '/vendor/vehicles/new',
    path: '/vendor/vehicles/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsIdTripRoute =
  AuthenticatedBookingsIdTripRouteImport.update({
    id: '/$id/trip',
    path: '/$id/trip',
    getParentRoute: () => AuthenticatedBookingsRoute,
  } as any)
const AuthenticatedBookingsIdDisputeRoute =
  AuthenticatedBookingsIdDisputeRouteImport.update({
    id: '/$id/dispute',
    path: '/$id/dispute',
    getParentRoute: () => AuthenticatedBookingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/drivers': typeof DriversRoute
  '/wash': typeof WashRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/driver-dashboard': typeof AuthenticatedDriverDashboardRoute
  '/hires': typeof AuthenticatedHiresRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/driver/$id': typeof DriverIdRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/messages/$bookingId': typeof AuthenticatedMessagesBookingIdRoute
  '/booking/qr/$code': typeof BookingQrCodeRoute
  '/vendor/': typeof AuthenticatedVendorIndexRoute
  '/bookings/$id/dispute': typeof AuthenticatedBookingsIdDisputeRoute
  '/bookings/$id/trip': typeof AuthenticatedBookingsIdTripRoute
  '/vendor/vehicles/new': typeof AuthenticatedVendorVehiclesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/drivers': typeof DriversRoute
  '/wash': typeof WashRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/driver-dashboard': typeof AuthenticatedDriverDashboardRoute
  '/hires': typeof AuthenticatedHiresRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/driver/$id': typeof DriverIdRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/messages/$bookingId': typeof AuthenticatedMessagesBookingIdRoute
  '/booking/qr/$code': typeof BookingQrCodeRoute
  '/vendor': typeof AuthenticatedVendorIndexRoute
  '/bookings/$id/dispute': typeof AuthenticatedBookingsIdDisputeRoute
  '/bookings/$id/trip': typeof AuthenticatedBookingsIdTripRoute
  '/vendor/vehicles/new': typeof AuthenticatedVendorVehiclesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/drivers': typeof DriversRoute
  '/wash': typeof WashRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/_authenticated/driver-dashboard': typeof AuthenticatedDriverDashboardRoute
  '/_authenticated/hires': typeof AuthenticatedHiresRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/driver/$id': typeof DriverIdRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/_authenticated/messages/$bookingId': typeof AuthenticatedMessagesBookingIdRoute
  '/booking/qr/$code': typeof BookingQrCodeRoute
  '/_authenticated/vendor/': typeof AuthenticatedVendorIndexRoute
  '/_authenticated/bookings/$id/dispute': typeof AuthenticatedBookingsIdDisputeRoute
  '/_authenticated/bookings/$id/trip': typeof AuthenticatedBookingsIdTripRoute
  '/_authenticated/vendor/vehicles/new': typeof AuthenticatedVendorVehiclesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/drivers'
    | '/wash'
    | '/admin'
    | '/bookings'
    | '/driver-dashboard'
    | '/hires'
    | '/profile'
    | '/wallet'
    | '/wishlist'
    | '/driver/$id'
    | '/vehicle/$id'
    | '/messages/$bookingId'
    | '/booking/qr/$code'
    | '/vendor/'
    | '/bookings/$id/dispute'
    | '/bookings/$id/trip'
    | '/vendor/vehicles/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/drivers'
    | '/wash'
    | '/admin'
    | '/bookings'
    | '/driver-dashboard'
    | '/hires'
    | '/profile'
    | '/wallet'
    | '/wishlist'
    | '/driver/$id'
    | '/vehicle/$id'
    | '/messages/$bookingId'
    | '/booking/qr/$code'
    | '/vendor'
    | '/bookings/$id/dispute'
    | '/bookings/$id/trip'
    | '/vendor/vehicles/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/drivers'
    | '/wash'
    | '/_authenticated/admin'
    | '/_authenticated/bookings'
    | '/_authenticated/driver-dashboard'
    | '/_authenticated/hires'
    | '/_authenticated/profile'
    | '/_authenticated/wallet'
    | '/_authenticated/wishlist'
    | '/driver/$id'
    | '/vehicle/$id'
    | '/_authenticated/messages/$bookingId'
    | '/booking/qr/$code'
    | '/_authenticated/vendor/'
    | '/_authenticated/bookings/$id/dispute'
    | '/_authenticated/bookings/$id/trip'
    | '/_authenticated/vendor/vehicles/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  DriversRoute: typeof DriversRoute
  WashRoute: typeof WashRoute
  DriverIdRoute: typeof DriverIdRoute
  VehicleIdRoute: typeof VehicleIdRoute
  BookingQrCodeRoute: typeof BookingQrCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wash': {
      id: '/wash'
      path: '/wash'
      fullPath: '/wash'
      preLoaderRoute: typeof WashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle/$id': {
      id: '/vehicle/$id'
      path: '/vehicle/$id'
      fullPath: '/vehicle/$id'
      preLoaderRoute: typeof VehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/$id': {
      id: '/driver/$id'
      path: '/driver/$id'
      fullPath: '/driver/$id'
      preLoaderRoute: typeof DriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hires': {
      id: '/_authenticated/hires'
      path: '/hires'
      fullPath: '/hires'
      preLoaderRoute: typeof AuthenticatedHiresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver-dashboard': {
      id: '/_authenticated/driver-dashboard'
      path: '/driver-dashboard'
      fullPath: '/driver-dashboard'
      preLoaderRoute: typeof AuthenticatedDriverDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/': {
      id: '/_authenticated/vendor/'
      path: '/vendor'
      fullPath: '/vendor/'
      preLoaderRoute: typeof AuthenticatedVendorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/booking/qr/$code': {
      id: '/booking/qr/$code'
      path: '/booking/qr/$code'
      fullPath: '/booking/qr/$code'
      preLoaderRoute: typeof BookingQrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/messages/$bookingId': {
      id: '/_authenticated/messages/$bookingId'
      path: '/messages/$bookingId'
      fullPath: '/messages/$bookingId'
      preLoaderRoute: typeof AuthenticatedMessagesBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/vehicles/new': {
      id: '/_authenticated/vendor/vehicles/new'
      path: '/vendor/vehicles/new'
      fullPath: '/vendor/vehicles/new'
      preLoaderRoute: typeof AuthenticatedVendorVehiclesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/$id/trip': {
      id: '/_authenticated/bookings/$id/trip'
      path: '/$id/trip'
      fullPath: '/bookings/$id/trip'
      preLoaderRoute: typeof AuthenticatedBookingsIdTripRouteImport
      parentRoute: typeof AuthenticatedBookingsRoute
    }
    '/_authenticated/bookings/$id/dispute': {
      id: '/_authenticated/bookings/$id/dispute'
      path: '/$id/dispute'
      fullPath: '/bookings/$id/dispute'
      preLoaderRoute: typeof AuthenticatedBookingsIdDisputeRouteImport
      parentRoute: typeof AuthenticatedBookingsRoute
    }
  }
}

interface AuthenticatedBookingsRouteChildren {
  AuthenticatedBookingsIdDisputeRoute: typeof AuthenticatedBookingsIdDisputeRoute
  AuthenticatedBookingsIdTripRoute: typeof AuthenticatedBookingsIdTripRoute
}

const AuthenticatedBookingsRouteChildren: AuthenticatedBookingsRouteChildren = {
  AuthenticatedBookingsIdDisputeRoute: AuthenticatedBookingsIdDisputeRoute,
  AuthenticatedBookingsIdTripRoute: AuthenticatedBookingsIdTripRoute,
}

const AuthenticatedBookingsRouteWithChildren =
  AuthenticatedBookingsRoute._addFileChildren(
    AuthenticatedBookingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRouteWithChildren
  AuthenticatedDriverDashboardRoute: typeof AuthenticatedDriverDashboardRoute
  AuthenticatedHiresRoute: typeof AuthenticatedHiresRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
  AuthenticatedMessagesBookingIdRoute: typeof AuthenticatedMessagesBookingIdRoute
  AuthenticatedVendorIndexRoute: typeof AuthenticatedVendorIndexRoute
  AuthenticatedVendorVehiclesNewRoute: typeof AuthenticatedVendorVehiclesNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRouteWithChildren,
  AuthenticatedDriverDashboardRoute: AuthenticatedDriverDashboardRoute,
  AuthenticatedHiresRoute: AuthenticatedHiresRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
  AuthenticatedMessagesBookingIdRoute: AuthenticatedMessagesBookingIdRoute,
  AuthenticatedVendorIndexRoute: AuthenticatedVendorIndexRoute,
  AuthenticatedVendorVehiclesNewRoute: AuthenticatedVendorVehiclesNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  DriversRoute: DriversRoute,
  WashRoute: WashRoute,
  DriverIdRoute: DriverIdRoute,
  VehicleIdRoute: VehicleIdRoute,
  BookingQrCodeRoute: BookingQrCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
